version: 0.2

phases:
  pre_build:
    commands:
      - npm install newman --global
      - npm install newman-reporter-html --global
  build:
    commands:
      - newman run -r html,cli VozPuck.postman_collection.json --reporter-html-export report.html

artifacts:
  files:
    - report.html